### ISSUE TITLE
Parabricks 4.3.1-1 failed

### ISSUE THREAD

**Issue by YettaWang** [Sydney-Informatics-Hub/Parabricks-Genomics-nf#31]
### Description of the bug

I want to use Parabricks to align methylation sequencing data, but I encounter the following error:cudaGetDevice() failed in geting device ID. Status: system not yet initialized, exiting
<img width="829" alt="屏幕截图 2024-07-02 180210" src="https://github.com/Sydney-Informatics-Hub/Parabricks-Genomics-nf/assets/108064090/23697d6e-db87-44bb-a49e-d64079c4e45f">

### Command that you ran and terminal output

```console
pbrun fq2bam_meth --ref hg38.fa --in-fq ../fq2bam_test/SRR13749850_1.fastq.gz ../fq2bam_test/SRR13749850_1.fastq.gz --out-ba SRR13749850.bam --num-gpus 1
```

**Comment by georgiesamaha** [comment]
Hi @YettaWang, this workflow implements Parabricks fq2bam (and other tools) for alignment of wgs short read data. We are not the developers of the Parabricks toolkit. Suggest you reach out to NVIDIA's Parabricks team directly for support: https://forums.developer.nvidia.com/c/healthcare/parabricks/290
